[package]
    name = "solana_program"
    version = "0.1.0"
    edition = "2021"

    [dependencies]
    solana-program = "1.18.26"
    borsh = "0.9.1"

    [dev-dependencies]
    solana-program-test = "2.2.7"
    solana-sdk = "2.2.2"

    [lib]
    crate-type = ["cdylib", "lib"]